In [1]:
import pandas as pd

In [2]:
df_sanctioned = pd.read_csv("Works Sanctioned.csv", skiprows=1)

C:\Users\sneha\AppData\Local\Temp\ipykernel_12856\2541761113.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sanctioned = pd.read_csv("Works Sanctioned.csv", skiprows=1)

In [3]:
df_sanctioned.head()

,Sr. No.,Work category,Work,State,IDA,Hon'ble Members of Parliament,Constituency,Work description,Recommended date,Sanction Date,Sanction Amount ( ₹ ),Work Status
0,1,Normal/Others,WS/ MP620/2024-2025/133166-Construction of bui...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan at Navalgund ...,08-Jul-24,09-Jul-24,497185.0,Physical Inspection
1,2,Trust and Society,WS/ MP620/2025-2026/133167-Construction of roo...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of College room of CBS Charitabl...,08-Jul-24,18-Sep-25,500000.0,Sanction
2,3,Trust and Society,WS/ MP620/2024-2025/133190-Construction of bui...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan of Veerashaiv...,08-Jul-24,23-Sep-24,450000.0,Sanction
3,4,Normal/Others,WS/ MP620/2025-2026/133191-Construction of bui...,Karnataka,HAVERI(DEPUTY COMMISSIONER HAVERI_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Maremma Cultural bhavan at Nee...,08-Jul-24,29-May-25,1500000.0,Work partially Completed
4,5,Normal/Others,WS/ MP620/2024-2025/133301-Construction of bui...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Cultural Bhavan at Kundagol TQ...,09-Jul-24,22-Aug-24,398009.0,Physical Inspection

In [4]:
df_sanctioned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78953 entries, 0 to 78952
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Sr. No.                        78953 non-null  object
 1   Work category                  78952 non-null  object
 2   Work                           78952 non-null  object
 3   State                          78952 non-null  object
 4   IDA                            78952 non-null  object
 5   Hon'ble Members of Parliament  78952 non-null  object
 6   Constituency                   78952 non-null  object
 7   Work description               78854 non-null  object
 8   Recommended date               78952 non-null  object
 9   Sanction Date                  78952 non-null  object
 10  Sanction Amount ( ₹ )          78952 non-null  float64
 11  Work Status                    78953 non-null  object
dtypes: float64(1), object(11)
memory usage: 7.2+ MB

In [5]:
df_sanctioned.shape

(78953, 12)

In [6]:
df_sanctioned.isnull().sum()

Sr. No.                           0
Work category                     1
Work                              1
State                             1
IDA                               1
Hon'ble Members of Parliament     1
Constituency                      1
Work description                 99
Recommended date                  1
Sanction Date                     1
Sanction Amount ( ₹ )             1
Work Status                       0
dtype: int64

In [7]:
df_sanctioned.columns

Index(['Sr. No.', 'Work category', 'Work', 'State', 'IDA',
       'Hon'ble Members of Parliament', 'Constituency', 'Work description',
       'Recommended date', 'Sanction Date', 'Sanction Amount ( ₹ )',
       'Work Status'],
      dtype='object')

In [8]:
df_sanctioned["Work"].head()

0    WS/ MP620/2024-2025/133166-Construction of bui...
1    WS/ MP620/2025-2026/133167-Construction of roo...
2    WS/ MP620/2024-2025/133190-Construction of bui...
3    WS/ MP620/2025-2026/133191-Construction of bui...
4    WS/ MP620/2024-2025/133301-Construction of bui...
Name: Work, dtype: object

In [9]:
df_sanctioned["Work"].iloc[0]

'WS/ MP620/2024-2025/133166-Construction of buildings for community cultural activities'

In [10]:
parts = df_sanctioned["Work"].str.split("/")

In [11]:
df_sanctioned["work_id"] = parts.str[0] + "/" + parts.str[1] + "/" + parts.str[2] + "/" + parts.str[3].str.split("-").str[0]

In [12]:
df_sanctioned[["Work", "work_id"]].head()

,Work,work_id
0,WS/ MP620/2024-2025/133166-Construction of bui...,WS/ MP620/2024-2025/133166
1,WS/ MP620/2025-2026/133167-Construction of roo...,WS/ MP620/2025-2026/133167
2,WS/ MP620/2024-2025/133190-Construction of bui...,WS/ MP620/2024-2025/133190
3,WS/ MP620/2025-2026/133191-Construction of bui...,WS/ MP620/2025-2026/133191
4,WS/ MP620/2024-2025/133301-Construction of bui...,WS/ MP620/2024-2025/133301

In [13]:
df_sanctioned["work_id"] = df_sanctioned["work_id"].str.replace(" ", "")

In [14]:
df_completed = pd.read_csv("Works Completed.csv", skiprows=1)

In [15]:
df_completed.head()

,Sr. No.,Work Category,Work,State,IDA,Work Description,Hon'ble Members of Parliament,Constituency,Image,Completion Date,Amount Disbursed ( ₹ )
0,1,Normal/Others,WS/MP418/2024-2025/133409-Construction of road...,Bihar,ARARIA(DISTRICT PLANNING OFFICER ARARIA_IDA),PCC Road from Permeshwar Bhagat house to Ramde...,Pradeep Kumar Singh,ARARIA,NaN,05-Sep-2024,448127
1,2,Normal/Others,WS/MP18152/2024-2025/133691-Construction of ro...,Punjab,FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA),Construction of MID DAY Meal Shed in Govt Prim...,SARABJEET SINGH KHALSA,FARIDKOT(SC),NaN,07-Apr-2025,300000
2,3,Normal/Others,WS/MP345/2024-2025/134140-Construction of road...,Kerala,KOLLAM(DISTRICT COLLECTOR KOLLAM_IDA),Concreting of road from Janathavayanasala - P...,Shri NK Premachandran,KOLLAM,NaN,12-Aug-2024,293492
3,4,Normal/Others,WS/MP18152/2024-2025/133686-Construction of ro...,Punjab,FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA),Construction of MID DAY Meal Shed in Govt Prim...,SARABJEET SINGH KHALSA,FARIDKOT(SC),NaN,07-Apr-2025,300000
4,5,Normal/Others,WS/MP18152/2024-2025/133690-Construction of ro...,Punjab,FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA),Construction of MID DAY Meal Shed in Govt Prim...,SARABJEET SINGH KHALSA,FARIDKOT(SC),NaN,07-Apr-2025,300000

In [16]:
df_completed.shape

(34222, 11)

In [17]:
df_completed.columns

Index(['Sr. No.', 'Work Category', 'Work', 'State', 'IDA', 'Work Description',
       'Hon'ble Members of Parliament', 'Constituency', 'Image',
       'Completion Date', 'Amount Disbursed ( ₹ )'],
      dtype='object')

In [18]:
df_completed.isnull().sum()

Sr. No.                             0
Work Category                       1
Work                                1
State                               1
IDA                                 1
Work Description                   80
Hon'ble Members of Parliament       1
Constituency                        1
Image                            9304
Completion Date                     1
Amount Disbursed ( ₹ )             87
dtype: int64

In [19]:
completed = df_completed.drop(columns=["Sr. No.", "Image"])

In [20]:
completed.head()

,Work Category,Work,State,IDA,Work Description,Hon'ble Members of Parliament,Constituency,Completion Date,Amount Disbursed ( ₹ )
0,Normal/Others,WS/MP418/2024-2025/133409-Construction of road...,Bihar,ARARIA(DISTRICT PLANNING OFFICER ARARIA_IDA),PCC Road from Permeshwar Bhagat house to Ramde...,Pradeep Kumar Singh,ARARIA,05-Sep-2024,448127
1,Normal/Others,WS/MP18152/2024-2025/133691-Construction of ro...,Punjab,FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA),Construction of MID DAY Meal Shed in Govt Prim...,SARABJEET SINGH KHALSA,FARIDKOT(SC),07-Apr-2025,300000
2,Normal/Others,WS/MP345/2024-2025/134140-Construction of road...,Kerala,KOLLAM(DISTRICT COLLECTOR KOLLAM_IDA),Concreting of road from Janathavayanasala - P...,Shri NK Premachandran,KOLLAM,12-Aug-2024,293492
3,Normal/Others,WS/MP18152/2024-2025/133686-Construction of ro...,Punjab,FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA),Construction of MID DAY Meal Shed in Govt Prim...,SARABJEET SINGH KHALSA,FARIDKOT(SC),07-Apr-2025,300000
4,Normal/Others,WS/MP18152/2024-2025/133690-Construction of ro...,Punjab,FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA),Construction of MID DAY Meal Shed in Govt Prim...,SARABJEET SINGH KHALSA,FARIDKOT(SC),07-Apr-2025,300000

In [21]:
parts = completed["Work"].str.split("/")

In [22]:
completed["work_id"] = parts.str[0] + "/" + parts.str[1] + "/" + parts.str[2] + "/" + parts.str[3].str.split("-").str[0]

In [23]:
completed[["Work", "work_id"]].head()

,Work,work_id
0,WS/MP418/2024-2025/133409-Construction of road...,WS/MP418/2024-2025/133409
1,WS/MP18152/2024-2025/133691-Construction of ro...,WS/MP18152/2024-2025/133691
2,WS/MP345/2024-2025/134140-Construction of road...,WS/MP345/2024-2025/134140
3,WS/MP18152/2024-2025/133686-Construction of ro...,WS/MP18152/2024-2025/133686
4,WS/MP18152/2024-2025/133690-Construction of ro...,WS/MP18152/2024-2025/133690

In [24]:
completed["work_id"] = completed["work_id"].str.replace(" ", "")

In [25]:
df_expenditure = pd.read_csv("Expenditure on Completed and On-going Works as on Date.csv", skiprows=1)

C:\Users\sneha\AppData\Local\Temp\ipykernel_12856\4276663540.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_expenditure = pd.read_csv("Expenditure on Completed and On-going Works as on Date.csv", skiprows=1)

In [26]:
df_expenditure.head()

,Sr. No.,State,Work,Work ID,IDA,Hon'ble Members of Parliament,Constituency,Expenditure Date,Vendor Name,Payment Status,Fund Disbursed Amount ( ₹ )
0,1,Uttar Pradesh,"Construction of roads, link roads, pathways or...",WS/MP18218/2025-2026/233777,GHAZIABAD(DISTRICT MAGISTRAE GHAZIABAD_IDA),ATUL GARG,GHAZIABAD,21-Aug-2026,DARSH BUILDCON,Payment In-Progress,799146.0
1,2,Uttar Pradesh,"Construction of roads, link roads, pathways or...",WS/MP18218/2025-2026/233878,GHAZIABAD(DISTRICT MAGISTRAE GHAZIABAD_IDA),ATUL GARG,GHAZIABAD,04-Aug-2026,DARSH BUILDCON,Payment In-Progress,832080.0
2,3,Uttar Pradesh,"Construction of roads, link roads, pathways or...",WS/MP18218/2025-2026/233781,GHAZIABAD(DISTRICT MAGISTRAE GHAZIABAD_IDA),ATUL GARG,GHAZIABAD,04-Aug-2026,DARSH BUILDCON,Payment In-Progress,498309.0
3,4,Odisha,Construction of community centers and communit...,WS/MP370/2024-2025/145537,Sundaragada(DISTRICT COLLECTOR SUNDARGARH_IDA),Shri Jual Oram,SUNDARGARH (ST),31-Aug-2026,MEMBER SECY OB AND OC WWB BBSR,Payment In-Progress,2000.0
4,5,Karnataka,Construction of additional rooms and halls in ...,WS/MP18082/2025-2026/242466,CHITRADURGA(DEPUTY COMMISSIONER CHITRADURGA_IDA),GOVIND MAKTHAPPA KARJOL,CHITRADURGA(SC),31-Aug-2026,KRIDL BHUSIRI ACCOUNT WORKS,Payment In-Progress,375000.0

In [27]:
df_expenditure.columns

Index(['Sr. No.', 'State', 'Work', 'Work ID', 'IDA',
       'Hon'ble Members of Parliament', 'Constituency', 'Expenditure Date',
       'Vendor Name', 'Payment Status', 'Fund Disbursed Amount ( ₹ )'],
      dtype='object')

In [28]:
expenditure = df_expenditure.drop(columns=["Sr. No."])

In [29]:
expenditure = expenditure.rename(columns={"Work ID": "work_id"})

In [30]:
expenditure.head()

,State,Work,work_id,IDA,Hon'ble Members of Parliament,Constituency,Expenditure Date,Vendor Name,Payment Status,Fund Disbursed Amount ( ₹ )
0,Uttar Pradesh,"Construction of roads, link roads, pathways or...",WS/MP18218/2025-2026/233777,GHAZIABAD(DISTRICT MAGISTRAE GHAZIABAD_IDA),ATUL GARG,GHAZIABAD,21-Aug-2026,DARSH BUILDCON,Payment In-Progress,799146.0
1,Uttar Pradesh,"Construction of roads, link roads, pathways or...",WS/MP18218/2025-2026/233878,GHAZIABAD(DISTRICT MAGISTRAE GHAZIABAD_IDA),ATUL GARG,GHAZIABAD,04-Aug-2026,DARSH BUILDCON,Payment In-Progress,832080.0
2,Uttar Pradesh,"Construction of roads, link roads, pathways or...",WS/MP18218/2025-2026/233781,GHAZIABAD(DISTRICT MAGISTRAE GHAZIABAD_IDA),ATUL GARG,GHAZIABAD,04-Aug-2026,DARSH BUILDCON,Payment In-Progress,498309.0
3,Odisha,Construction of community centers and communit...,WS/MP370/2024-2025/145537,Sundaragada(DISTRICT COLLECTOR SUNDARGARH_IDA),Shri Jual Oram,SUNDARGARH (ST),31-Aug-2026,MEMBER SECY OB AND OC WWB BBSR,Payment In-Progress,2000.0
4,Karnataka,Construction of additional rooms and halls in ...,WS/MP18082/2025-2026/242466,CHITRADURGA(DEPUTY COMMISSIONER CHITRADURGA_IDA),GOVIND MAKTHAPPA KARJOL,CHITRADURGA(SC),31-Aug-2026,KRIDL BHUSIRI ACCOUNT WORKS,Payment In-Progress,375000.0

In [31]:
expenditure.shape

(83765, 10)

In [32]:
expenditure["work_id"] = expenditure["work_id"].str.replace(" ", "")

In [33]:
# Counts how many Work IDs are common between Sanctioned and Completed
len(set(df_sanctioned["work_id"]) & set(completed["work_id"]))

34221

In [34]:
len(set(df_sanctioned["work_id"]) & set(expenditure["work_id"]))

56339

In [35]:
# to count duplicate work id in expenditure 
expenditure["work_id"].duplicated().sum()

np.int64(27425)

In [36]:
expenditure.isnull().sum()

State                            1
Work                             1
work_id                          1
IDA                              1
Hon'ble Members of Parliament    1
Constituency                     1
Expenditure Date                 1
Vendor Name                      1
Payment Status                   1
Fund Disbursed Amount ( ₹ )      0
dtype: int64

In [37]:
expenditure = expenditure.dropna(subset=["work_id"])

In [38]:
df_sanctioned["work_id"].isnull().sum()

np.int64(1)

In [39]:
df_sanctioned = df_sanctioned.dropna(subset=["work_id"])

In [40]:
completed["work_id"].isnull().sum()

np.int64(1)

In [41]:
completed = completed.dropna(subset=["work_id"])

In [42]:
# Combines sanctioned and completed information using work_id, keeping all sanctioned works
merged = pd.merge(df_sanctioned, completed, on="work_id", how="left")

In [43]:
merged.shape

(78952, 22)

In [44]:
merged.head()

,Sr. No.,Work category,Work_x,State_x,IDA_x,Hon'ble Members of Parliament_x,Constituency_x,Work description,Recommended date,Sanction Date,...,work_id,Work Category,Work_y,State_y,IDA_y,Work Description,Hon'ble Members of Parliament_y,Constituency_y,Completion Date,Amount Disbursed ( ₹ )
0,1,Normal/Others,WS/ MP620/2024-2025/133166-Construction of bui...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan at Navalgund ...,08-Jul-24,09-Jul-24,...,WS/MP620/2024-2025/133166,Normal/Others,WS/ MP620/2024-2025/133166-Construction of bui...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Construction of Community Bhavan at Navalgund ...,Pralhad Venkatesh Joshi,DHARWAD,14-Oct-2024,497185
1,2,Trust and Society,WS/ MP620/2025-2026/133167-Construction of roo...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of College room of CBS Charitabl...,08-Jul-24,18-Sep-25,...,WS/MP620/2025-2026/133167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Trust and Society,WS/ MP620/2024-2025/133190-Construction of bui...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan of Veerashaiv...,08-Jul-24,23-Sep-24,...,WS/MP620/2024-2025/133190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Normal/Others,WS/ MP620/2025-2026/133191-Construction of bui...,Karnataka,HAVERI(DEPUTY COMMISSIONER HAVERI_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Maremma Cultural bhavan at Nee...,08-Jul-24,29-May-25,...,WS/MP620/2025-2026/133191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Normal/Others,WS/ MP620/2024-2025/133301-Construction of bui...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Cultural Bhavan at Kundagol TQ...,09-Jul-24,22-Aug-24,...,WS/MP620/2024-2025/133301,Normal/Others,WS/ MP620/2024-2025/133301-Construction of bui...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Construction of Cultural Bhavan at Kundagol TQ...,Pralhad Venkatesh Joshi,DHARWAD,03-Feb-2025,398009

In [45]:
merged.columns

Index(['Sr. No.', 'Work category', 'Work_x', 'State_x', 'IDA_x',
       'Hon'ble Members of Parliament_x', 'Constituency_x', 'Work description',
       'Recommended date', 'Sanction Date', 'Sanction Amount ( ₹ )',
       'Work Status', 'work_id', 'Work Category', 'Work_y', 'State_y', 'IDA_y',
       'Work Description', 'Hon'ble Members of Parliament_y', 'Constituency_y',
       'Completion Date', 'Amount Disbursed ( ₹ )'],
      dtype='object')

In [46]:
final = merged[[
    "work_id",
    "Work category",
    "Work_x",
    "State_x",
    "IDA_x",
    "Hon'ble Members of Parliament_x",
    "Constituency_x",
    "Work description",
    "Recommended date",
    "Sanction Date",
    "Sanction Amount ( ₹ )",
    "Work Status",
    "Completion Date",
    "Amount Disbursed ( ₹ )"
]]

In [47]:
final.shape

(78952, 14)

In [48]:
final.head()

,work_id,Work category,Work_x,State_x,IDA_x,Hon'ble Members of Parliament_x,Constituency_x,Work description,Recommended date,Sanction Date,Sanction Amount ( ₹ ),Work Status,Completion Date,Amount Disbursed ( ₹ )
0,WS/MP620/2024-2025/133166,Normal/Others,WS/ MP620/2024-2025/133166-Construction of bui...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan at Navalgund ...,08-Jul-24,09-Jul-24,497185.0,Physical Inspection,14-Oct-2024,497185
1,WS/MP620/2025-2026/133167,Trust and Society,WS/ MP620/2025-2026/133167-Construction of roo...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of College room of CBS Charitabl...,08-Jul-24,18-Sep-25,500000.0,Sanction,NaN,NaN
2,WS/MP620/2024-2025/133190,Trust and Society,WS/ MP620/2024-2025/133190-Construction of bui...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan of Veerashaiv...,08-Jul-24,23-Sep-24,450000.0,Sanction,NaN,NaN
3,WS/MP620/2025-2026/133191,Normal/Others,WS/ MP620/2025-2026/133191-Construction of bui...,Karnataka,HAVERI(DEPUTY COMMISSIONER HAVERI_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Maremma Cultural bhavan at Nee...,08-Jul-24,29-May-25,1500000.0,Work partially Completed,NaN,NaN
4,WS/MP620/2024-2025/133301,Normal/Others,WS/ MP620/2024-2025/133301-Construction of bui...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Cultural Bhavan at Kundagol TQ...,09-Jul-24,22-Aug-24,398009.0,Physical Inspection,03-Feb-2025,398009

In [49]:
exp_total = expenditure.groupby("work_id")["Fund Disbursed Amount ( ₹ )"].sum()

In [50]:
exp_total.head()

work_id
WS/MP005/2024-2025/145074    450000.0
WS/MP005/2024-2025/175217    250000.0
WS/MP005/2024-2025/175218    149865.0
WS/MP005/2024-2025/175230    100000.0
WS/MP005/2024-2025/175232     50000.0
Name: Fund Disbursed Amount ( ₹ ), dtype: float64

In [51]:
final = pd.merge(final, exp_total, on="work_id", how="left")

In [52]:
final.head()

,work_id,Work category,Work_x,State_x,IDA_x,Hon'ble Members of Parliament_x,Constituency_x,Work description,Recommended date,Sanction Date,Sanction Amount ( ₹ ),Work Status,Completion Date,Amount Disbursed ( ₹ ),Fund Disbursed Amount ( ₹ )
0,WS/MP620/2024-2025/133166,Normal/Others,WS/ MP620/2024-2025/133166-Construction of bui...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan at Navalgund ...,08-Jul-24,09-Jul-24,497185.0,Physical Inspection,14-Oct-2024,497185,497185.0
1,WS/MP620/2025-2026/133167,Trust and Society,WS/ MP620/2025-2026/133167-Construction of roo...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of College room of CBS Charitabl...,08-Jul-24,18-Sep-25,500000.0,Sanction,NaN,NaN,NaN
2,WS/MP620/2024-2025/133190,Trust and Society,WS/ MP620/2024-2025/133190-Construction of bui...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan of Veerashaiv...,08-Jul-24,23-Sep-24,450000.0,Sanction,NaN,NaN,NaN
3,WS/MP620/2025-2026/133191,Normal/Others,WS/ MP620/2025-2026/133191-Construction of bui...,Karnataka,HAVERI(DEPUTY COMMISSIONER HAVERI_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Maremma Cultural bhavan at Nee...,08-Jul-24,29-May-25,1500000.0,Work partially Completed,NaN,NaN,850909.0
4,WS/MP620/2024-2025/133301,Normal/Others,WS/ MP620/2024-2025/133301-Construction of bui...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Cultural Bhavan at Kundagol TQ...,09-Jul-24,22-Aug-24,398009.0,Physical Inspection,03-Feb-2025,398009,398009.0

In [53]:
final["Fund Disbursed Amount ( ₹ )"].isnull().sum()

np.int64(22613)

In [54]:
final["Completion Date"].isnull().sum()

np.int64(44731)

In [55]:
final.shape

(78952, 15)

**Feature Engineering**

In [56]:
# Expenditure Ratio: Calculate how much of the sanctioned amount has been spent
final["expenditure_ratio"] = final["Fund Disbursed Amount ( ₹ )"] / final["Sanction Amount ( ₹ )"]

In [57]:
# View the expenditure ratio
final[["work_id", "Sanction Amount ( ₹ )", "Fund Disbursed Amount ( ₹ )", "expenditure_ratio"]].head()

,work_id,Sanction Amount ( ₹ ),Fund Disbursed Amount ( ₹ ),expenditure_ratio
0,WS/MP620/2024-2025/133166,497185.0,497185.0,1.000000
1,WS/MP620/2025-2026/133167,500000.0,NaN,NaN
2,WS/MP620/2024-2025/133190,450000.0,NaN,NaN
3,WS/MP620/2025-2026/133191,1500000.0,850909.0,0.567273
4,WS/MP620/2024-2025/133301,398009.0,398009.0,1.000000

In [58]:
# Remaining Amount: the amount left after expenditure
final["remaining_amount"] = final["Sanction Amount ( ₹ )"] - final["Fund Disbursed Amount ( ₹ )"]

In [59]:
# Check the remaining amount
final[["work_id", "Sanction Amount ( ₹ )", "Fund Disbursed Amount ( ₹ )", "remaining_amount"]].head()

,work_id,Sanction Amount ( ₹ ),Fund Disbursed Amount ( ₹ ),remaining_amount
0,WS/MP620/2024-2025/133166,497185.0,497185.0,0.0
1,WS/MP620/2025-2026/133167,500000.0,NaN,NaN
2,WS/MP620/2024-2025/133190,450000.0,NaN,NaN
3,WS/MP620/2025-2026/133191,1500000.0,850909.0,649091.0
4,WS/MP620/2024-2025/133301,398009.0,398009.0,0.0

In [60]:
# Convert sanction and completion dates to date format
final["Sanction Date"] = pd.to_datetime(final["Sanction Date"])
final["Completion Date"] = pd.to_datetime(final["Completion Date"])

C:\Users\sneha\AppData\Local\Temp\ipykernel_12856\4265662861.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  final["Sanction Date"] = pd.to_datetime(final["Sanction Date"])

In [61]:
# Convert dates using the known date format
final["Sanction Date"] = pd.to_datetime(final["Sanction Date"], format="%d-%b-%y", errors="coerce")

In [62]:
# Convert completion dates
final["Completion Date"] = pd.to_datetime(final["Completion Date"], format="%d-%b-%Y", errors="coerce")

In [63]:
# Execution time: how long a work takes from sanction to completion.
# Completion time = Completion Date − Sanction Date

In [64]:
# Calculate days taken to complete each work
final["completion_days"] = (final["Completion Date"] - final["Sanction Date"]).dt.days

In [65]:
# Check completion duration
final[["work_id", "Sanction Date", "Completion Date", "completion_days"]].head()

                     work_id Sanction Date Completion Date  completion_days
0  WS/MP620/2024-2025/133166    2024-07-09      2024-10-14             97.0
1  WS/MP620/2025-2026/133167    2025-09-18             NaT              NaN
2  WS/MP620/2024-2025/133190    2024-09-23             NaT              NaN
3  WS/MP620/2025-2026/133191    2025-05-29             NaT              NaN
4  WS/MP620/2024-2025/133301    2024-08-22      2025-02-03            165.0

In [66]:
# sanction amount vs expenditure
# Identify works where expenditure exceeds sanctioned amount
final["over_expenditure"] = final["expenditure_ratio"] > 1

In [67]:
# Flag only works with available expenditure data
final["over_expenditure"] = final["expenditure_ratio"].where(
    final["expenditure_ratio"].isna(),
    final["expenditure_ratio"] > 1
)

In [68]:
# Count each over-expenditure status
final["over_expenditure"].value_counts(dropna=False)

over_expenditure
False    56339
NaN      22613
Name: count, dtype: int64

In [69]:
# Convert recommended dates to proper date format
final["Recommended date"] = pd.to_datetime(final["Recommended date"], format="%d-%b-%y", errors="coerce")

In [70]:
# completion delay: a project without a completion date may still be running.
# Calculate days between recommendation and sanction
final["sanction_delay_days"] = (final["Sanction Date"] - final["Recommended date"]).dt.days

In [71]:
# Check the calculated delay
final[["work_id", "Recommended date", "Sanction Date", "sanction_delay_days"]].head()

,work_id,Recommended date,Sanction Date,sanction_delay_days
0,WS/MP620/2024-2025/133166,2024-07-08,2024-07-09,1
1,WS/MP620/2025-2026/133167,2024-07-08,2025-09-18,437
2,WS/MP620/2024-2025/133190,2024-07-08,2024-09-23,77
3,WS/MP620/2025-2026/133191,2024-07-08,2025-05-29,325
4,WS/MP620/2024-2025/133301,2024-07-09,2024-08-22,44

In [72]:
# Understanding the overall delay distribution
# Check basic statistics of sanction delays
final["sanction_delay_days"].describe()

count    78952.000000
mean       106.492464
std         95.186133
min          0.000000
25%         39.000000
50%         79.000000
75%        140.000000
max        732.000000
Name: sanction_delay_days, dtype: float64

In [73]:
# Flag works with unusually high sanction delay
final["long_sanction_delay"] = final["sanction_delay_days"] > 140

In [74]:
# Count long and normal sanction delays
final["long_sanction_delay"].value_counts()

long_sanction_delay
False    59383
True     19569
Name: count, dtype: int64

In [75]:
# Check how long completed works usually take
final["completion_days"].describe()

count    34221.000000
mean       175.638409
std        131.742023
min          0.000000
25%         72.000000
50%        152.000000
75%        260.000000
max        719.000000
Name: completion_days, dtype: float64

In [76]:
# Count payment transactions for each work
payment_count = expenditure.groupby("work_id").size()

In [77]:
# Add payment count to the master dataset
final = final.merge(payment_count.rename("payment_count"), on="work_id", how="left")

In [78]:
# Count different vendors for each work
vendor_count = expenditure.groupby("work_id")["Vendor Name"].nunique()

In [79]:
# Add vendor count to the master dataset
final = final.merge(vendor_count.rename("vendor_count"), on="work_id", how="left")

In [80]:
# Calculate the average payment for each work
avg_payment = expenditure.groupby("work_id")["Fund Disbursed Amount ( ₹ )"].mean()

In [81]:
# Add average payment to the master dataset
final = final.merge(avg_payment.rename("avg_payment"), on="work_id", how="left")

In [82]:
# Find the largest payment made for each work
max_payment = expenditure.groupby("work_id")["Fund Disbursed Amount ( ₹ )"].max()

In [83]:
# Add maximum payment to the master dataset
final = final.merge(max_payment.rename("max_payment"), on="work_id", how="left")

In [84]:
# Check the different work status categories
final["Work Status"].value_counts()

Work Status
Physical Inspection         34051
Sanction                    20276
Vendor Identification       11558
Work partially Completed     7994
Work Completed               4260
Time Estimation               813
Name: count, dtype: int64

In [85]:
# Mark whether the work is officially completed
final["is_completed"] = final["Work Status"] == "Work Completed"

In [86]:
# Count completed and non-completed works
final["is_completed"].value_counts()

is_completed
False    74692
True      4260
Name: count, dtype: int64

In [87]:
# Calculate how long each work has been running
today = pd.Timestamp("2026-09-03")
final["project_age_days"] = (today - final["Sanction Date"]).dt.days

In [88]:
# Check project age
final[["work_id", "Sanction Date", "Completion Date", "project_age_days"]].head()

                     work_id Sanction Date Completion Date  project_age_days
0  WS/MP620/2024-2025/133166    2024-07-09      2024-10-14               786
1  WS/MP620/2025-2026/133167    2025-09-18             NaT               350
2  WS/MP620/2024-2025/133190    2024-09-23             NaT               710
3  WS/MP620/2025-2026/133191    2025-05-29             NaT               462
4  WS/MP620/2024-2025/133301    2024-08-22      2025-02-03               742

In [89]:
# Count payment statuses for each work
payment_status = expenditure.groupby(["work_id", "Payment Status"]).size().unstack(fill_value=0)

In [90]:
# View payment status counts
payment_status.head()

Payment Status             Payment In-Progress  Payment Success
work_id
WS/MP005/2024-2025/145074                    0                1
WS/MP005/2024-2025/175217                    0                1
WS/MP005/2024-2025/175218                    0                1
WS/MP005/2024-2025/175230                    0                1
WS/MP005/2024-2025/175232                    0                1

In [91]:
# Add payment status counts to the master dataset
final = final.merge(payment_status, on="work_id", how="left")

In [92]:
# Check the new payment status features
final[["work_id", "Payment In-Progress", "Payment Success"]].head()

                     work_id  Payment In-Progress  Payment Success
0  WS/MP620/2024-2025/133166                  0.0              1.0
1  WS/MP620/2025-2026/133167                  NaN              NaN
2  WS/MP620/2024-2025/133190                  NaN              NaN
3  WS/MP620/2025-2026/133191                  0.0              1.0
4  WS/MP620/2024-2025/133301                  0.0              1.0

In [93]:
# Expenditure Timing: calculates how many days after sanction the first payment was made.
# Find the first payment date for each work
first_payment = expenditure.groupby("work_id")["Expenditure Date"].min()

In [94]:
# Add first payment date to the master dataset
final = final.merge(first_payment.rename("first_payment_date"), on="work_id", how="left")

In [95]:
# Convert first payment date to date format
final["first_payment_date"] = pd.to_datetime(final["first_payment_date"], errors="coerce")

In [96]:
# Calculate days from sanction to first payment
final["first_payment_delay_days"] = (final["first_payment_date"] - final["Sanction Date"]).dt.days

In [97]:
# Category average: sanction amount compared with the average sanction amount for its work category.
# Find average sanctioned amount for each work category
category_avg = final.groupby("Work category")["Sanction Amount ( ₹ )"].transform("mean")

In [98]:
# Compare each work with its category average
final["cost_vs_category_avg"] = final["Sanction Amount ( ₹ )"] / category_avg

In [99]:
# View all columns in the master dataset
final.columns

Index(['work_id', 'Work category', 'Work_x', 'State_x', 'IDA_x',
       'Hon'ble Members of Parliament_x', 'Constituency_x', 'Work description',
       'Recommended date', 'Sanction Date', 'Sanction Amount ( ₹ )',
       'Work Status', 'Completion Date', 'Amount Disbursed ( ₹ )',
       'Fund Disbursed Amount ( ₹ )', 'expenditure_ratio', 'remaining_amount',
       'completion_days', 'over_expenditure', 'sanction_delay_days',
       'long_sanction_delay', 'payment_count', 'vendor_count', 'avg_payment',
       'max_payment', 'is_completed', 'project_age_days',
       'Payment In-Progress', 'Payment Success', 'first_payment_date',
       'first_payment_delay_days', 'cost_vs_category_avg'],
      dtype='object')

**Final Data Preprocessing**

In [100]:
# Remove duplicate columns created during merging
final = final.drop(columns=[
    "Work Category", "Work_y", "State_y", "IDA_y",
    "Work Description_y", "Hon'ble Members of Parliament_y",
    "Constituency_y"
], errors="ignore")

In [101]:
final.columns

Index(['work_id', 'Work category', 'Work_x', 'State_x', 'IDA_x',
       'Hon'ble Members of Parliament_x', 'Constituency_x', 'Work description',
       'Recommended date', 'Sanction Date', 'Sanction Amount ( ₹ )',
       'Work Status', 'Completion Date', 'Amount Disbursed ( ₹ )',
       'Fund Disbursed Amount ( ₹ )', 'expenditure_ratio', 'remaining_amount',
       'completion_days', 'over_expenditure', 'sanction_delay_days',
       'long_sanction_delay', 'payment_count', 'vendor_count', 'avg_payment',
       'max_payment', 'is_completed', 'project_age_days',
       'Payment In-Progress', 'Payment Success', 'first_payment_date',
       'first_payment_delay_days', 'cost_vs_category_avg'],
      dtype='object')

Feature Selection

In [102]:
# Select numerical features for anomaly detection
ml_features = [
    "Sanction Amount ( ₹ )",
    "Fund Disbursed Amount ( ₹ )",
    "expenditure_ratio",
    "remaining_amount",
    "completion_days",
    "sanction_delay_days",
    "payment_count",
    "vendor_count",
    "avg_payment",
    "max_payment",
    "project_age_days",
    "Payment In-Progress",
    "Payment Success",
    "first_payment_delay_days",
    "cost_vs_category_avg"
]

In [103]:
# View the selected ML features
final[ml_features].head()

,Sanction Amount ( ₹ ),Fund Disbursed Amount ( ₹ ),expenditure_ratio,remaining_amount,completion_days,sanction_delay_days,payment_count,vendor_count,avg_payment,max_payment,project_age_days,Payment In-Progress,Payment Success,first_payment_delay_days,cost_vs_category_avg
0,497185.0,497185.0,1.000000,0.0,97.0,1,1.0,1.0,497185.0,497185.0,786,0.0,1.0,98.0,0.950233
1,500000.0,NaN,NaN,NaN,NaN,437,NaN,NaN,NaN,NaN,350,NaN,NaN,NaN,0.511002
2,450000.0,NaN,NaN,NaN,NaN,77,NaN,NaN,NaN,NaN,710,NaN,NaN,NaN,0.459902
3,1500000.0,850909.0,0.567273,649091.0,NaN,325,1.0,1.0,850909.0,850909.0,462,0.0,1.0,280.0,2.866839
4,398009.0,398009.0,1.000000,0.0,165.0,44,1.0,1.0,398009.0,398009.0,742,0.0,1.0,281.0,0.760685

Handling Missing Values

In [104]:
# Check missing values in the selected ML features
final[ml_features].isnull().sum()

Sanction Amount ( ₹ )              0
Fund Disbursed Amount ( ₹ )    22613
expenditure_ratio              22613
remaining_amount               22613
completion_days                44731
sanction_delay_days                0
payment_count                  22613
vendor_count                   22613
avg_payment                    22613
max_payment                    22613
project_age_days                   0
Payment In-Progress            22613
Payment Success                22613
first_payment_delay_days       22613
cost_vs_category_avg               0
dtype: int64

In [105]:
# Replace missing expenditure/payment values with 0
payment_features = [
    "Fund Disbursed Amount ( ₹ )",
    "expenditure_ratio",
    "remaining_amount",
    "payment_count",
    "vendor_count",
    "avg_payment",
    "max_payment",
    "Payment In-Progress",
    "Payment Success",
    "first_payment_delay_days"
]

final[payment_features] = final[payment_features].fillna(0)

In [106]:
# Use completion time for completed works and current age for ongoing works
final["duration_days"] = final["completion_days"].fillna(final["project_age_days"])

In [107]:
# Duration days: calculates how many days the project has been running from its sanction date until either completion or today.
# Check the new duration feature
final[["work_id", "completion_days", "project_age_days", "duration_days"]].head()

                     work_id  completion_days  project_age_days  duration_days
0  WS/MP620/2024-2025/133166             97.0               786           97.0
1  WS/MP620/2025-2026/133167              NaN               350          350.0
2  WS/MP620/2024-2025/133190              NaN               710          710.0
3  WS/MP620/2025-2026/133191              NaN               462          462.0
4  WS/MP620/2024-2025/133301            165.0               742          165.0

In [108]:
# Define the final numerical features for ML
ml_features = [
    "Sanction Amount ( ₹ )",
    "Fund Disbursed Amount ( ₹ )",
    "expenditure_ratio",
    "remaining_amount",
    "duration_days",
    "sanction_delay_days",
    "payment_count",
    "vendor_count",
    "avg_payment",
    "max_payment",
    "project_age_days",
    "Payment In-Progress",
    "Payment Success",
    "first_payment_delay_days",
    "cost_vs_category_avg"
]

In [109]:
# Check for any missing values before model training
final[ml_features].isnull().sum()

Sanction Amount ( ₹ )          0
Fund Disbursed Amount ( ₹ )    0
expenditure_ratio              0
remaining_amount               0
duration_days                  0
sanction_delay_days            0
payment_count                  0
vendor_count                   0
avg_payment                    0
max_payment                    0
project_age_days               0
Payment In-Progress            0
Payment Success                0
first_payment_delay_days       0
cost_vs_category_avg           0
dtype: int64

In [110]:
# creating a separate dataframe containing only the 15 features. This keeps the original final dataset untouched.

In [111]:
# Create the dataset that will be given to the ML model
X = final[ml_features].copy()

In [112]:
# Check the shape of the ML dataset
X.shape

(78952, 15)

Standardization

In [113]:
# Standardize all ML features to a comparable scale
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [114]:
# Check the shape of the scaled data
X_scaled.shape

(78952, 15)

**Isolation Forest anomaly detection model**

In [115]:
# Create the Isolation Forest anomaly detection model
from sklearn.ensemble import IsolationForest

model = IsolationForest(
    n_estimators=200,
    contamination=0.05,
    random_state=42
)

In [116]:
# Train Isolation Forest on the prepared MPLADS data
model.fit(X_scaled)

IsolationForest(contamination=0.05, n_estimators=200, random_state=42)

Generating Anomaly Predictions

In [117]:
# Generate anomaly predictions for every work
final["anomaly_prediction"] = model.predict(X_scaled)

In [118]:
# Count normal and anomalous works
final["anomaly_prediction"].value_counts()

anomaly_prediction
 1    75004
-1     3948
Name: count, dtype: int64

Anomaly Score

In [119]:
# Calculate how unusual each work is
final["anomaly_score"] = model.decision_function(X_scaled)

In [120]:
# View the most unusual works
final.sort_values("anomaly_score").head()

,work_id,Work category,Work_x,State_x,IDA_x,Hon'ble Members of Parliament_x,Constituency_x,Work description,Recommended date,Sanction Date,...,is_completed,project_age_days,Payment In-Progress,Payment Success,first_payment_date,first_payment_delay_days,cost_vs_category_avg,duration_days,anomaly_prediction,anomaly_score
77185,WS/MP507/2026-2027/290535,Normal/Others,WS/MP507/2026-2027/290535-Lighting of public s...,Uttar Pradesh,SITAPUR(DISTRICT MAGISTRATE SITAPUR_IDA),Ashok Kumar Rawat,MISRIKH(SC),supply and installation of led semihigh mast l...,2026-06-30,2026-08-19,...,False,15,8.0,0.0,2026-08-24,5.0,95.064393,15.0,-1,-0.264434
42488,WS/MP18198/2025-2026/214766,Normal/Others,WS/MP18198/2025-2026/214766-Construction of ro...,Uttar Pradesh,PRAYAGRAJ(DISTRICT MAGISTRAE ALLAHABAD_IDA),UJJWAL RAMAN SINGH,ALLAHABAD,Allahabad loksabha Kshetra Roads construction,2025-07-04,2025-08-12,...,False,387,4.0,18.0,2026-04-04,235.0,32.026418,387.0,-1,-0.253937
9828,WS/MP18249/2025-2026/153601,Normal/Others,WS/MP18249/2025-2026/153601-Construction of ro...,West Bengal,North 24 Parganas(DISTRICT MAGISTRATE NORTH TW...,PARTHA BHOWMICK,BARRACKPUR,Development of Naihati State General Hospital.,2024-11-21,2025-08-18,...,False,381,0.0,2.0,2026-02-23,189.0,38.224525,381.0,-1,-0.244282
31991,WS/MP507/2025-2026/196288,Normal/Others,WS/MP507/2025-2026/196288-Lighting of public s...,Uttar Pradesh,KANPUR NAGAR(DISTRICT MAGISTRAE KANPUR NAGAR_IDA),Ashok Kumar Rawat,MISRIKH(SC),SUPPLY AND INSTALLATION OF LED SEMI HIGH MAST ...,2025-05-03,2025-06-26,...,False,434,0.0,4.0,2026-04-15,293.0,90.729824,434.0,-1,-0.242891
9829,WS/MP18249/2025-2026/153603,Normal/Others,WS/MP18249/2025-2026/153603-Construction of ro...,West Bengal,North 24 Parganas(DISTRICT MAGISTRATE NORTH TW...,PARTHA BHOWMICK,BARRACKPUR,Development of Bhatpara State General Hospital.,2024-11-21,2025-08-18,...,False,381,0.0,4.0,2025-09-19,32.0,38.224525,381.0,-1,-0.237893

Risk Level Creation

In [121]:
# Convert model prediction into a simple risk label
final["risk_level"] = final["anomaly_prediction"].map({
    1: "Normal",
    -1: "High Risk"
})

In [122]:
# Count each risk level
final["risk_level"].value_counts()

risk_level
Normal       75004
High Risk     3948
Name: count, dtype: int64

Highest Risk Works

In [123]:
# Show the most unusual works
high_risk = final[final["risk_level"] == "High Risk"].sort_values("anomaly_score")

high_risk.head(10)

,work_id,Work category,Work_x,State_x,IDA_x,Hon'ble Members of Parliament_x,Constituency_x,Work description,Recommended date,Sanction Date,...,project_age_days,Payment In-Progress,Payment Success,first_payment_date,first_payment_delay_days,cost_vs_category_avg,duration_days,anomaly_prediction,anomaly_score,risk_level
77185,WS/MP507/2026-2027/290535,Normal/Others,WS/MP507/2026-2027/290535-Lighting of public s...,Uttar Pradesh,SITAPUR(DISTRICT MAGISTRATE SITAPUR_IDA),Ashok Kumar Rawat,MISRIKH(SC),supply and installation of led semihigh mast l...,2026-06-30,2026-08-19,...,15,8.0,0.0,2026-08-24,5.0,95.064393,15.0,-1,-0.264434,High Risk
42488,WS/MP18198/2025-2026/214766,Normal/Others,WS/MP18198/2025-2026/214766-Construction of ro...,Uttar Pradesh,PRAYAGRAJ(DISTRICT MAGISTRAE ALLAHABAD_IDA),UJJWAL RAMAN SINGH,ALLAHABAD,Allahabad loksabha Kshetra Roads construction,2025-07-04,2025-08-12,...,387,4.0,18.0,2026-04-04,235.0,32.026418,387.0,-1,-0.253937,High Risk
9828,WS/MP18249/2025-2026/153601,Normal/Others,WS/MP18249/2025-2026/153601-Construction of ro...,West Bengal,North 24 Parganas(DISTRICT MAGISTRATE NORTH TW...,PARTHA BHOWMICK,BARRACKPUR,Development of Naihati State General Hospital.,2024-11-21,2025-08-18,...,381,0.0,2.0,2026-02-23,189.0,38.224525,381.0,-1,-0.244282,High Risk
31991,WS/MP507/2025-2026/196288,Normal/Others,WS/MP507/2025-2026/196288-Lighting of public s...,Uttar Pradesh,KANPUR NAGAR(DISTRICT MAGISTRAE KANPUR NAGAR_IDA),Ashok Kumar Rawat,MISRIKH(SC),SUPPLY AND INSTALLATION OF LED SEMI HIGH MAST ...,2025-05-03,2025-06-26,...,434,0.0,4.0,2026-04-15,293.0,90.729824,434.0,-1,-0.242891,High Risk
9829,WS/MP18249/2025-2026/153603,Normal/Others,WS/MP18249/2025-2026/153603-Construction of ro...,West Bengal,North 24 Parganas(DISTRICT MAGISTRATE NORTH TW...,PARTHA BHOWMICK,BARRACKPUR,Development of Bhatpara State General Hospital.,2024-11-21,2025-08-18,...,381,0.0,4.0,2025-09-19,32.0,38.224525,381.0,-1,-0.237893,High Risk
50171,WS/MP817/2025-2026/229416,Normal/Others,WS/MP817/2025-2026/229416-Lighting of public s...,Uttar Pradesh,MIRZAPUR(DISTRICT MAGISTRATE MIRZAPUR_IDA),Smt Anupriya Patel,MIRZAPUR,works recomonded in letter no 216 for jamalpur...,2025-08-26,2025-09-11,...,357,0.0,2.0,2026-08-06,329.0,42.297348,357.0,-1,-0.236346,High Risk
43541,WS/MP18279/2025-2026/216827,Normal/Others,WS/MP18279/2025-2026/216827-Purchase of hospit...,Lakshadweep,LAKSHADWEEP DISTRICT(COLLECTOR CUM DEV COMMISS...,MUHAMMED HAMDULLAH SAYEED,LAKSHADWEEP(ST),Procurement of a 32 slice CT Scan Machine to t...,2025-07-10,2025-08-06,...,393,0.0,1.0,2026-03-12,218.0,86.005181,393.0,-1,-0.233450,High Risk
274,WS/MP492/2024-2025/134984,Normal/Others,WS/MP492/2024-2025/134984-Lighting of public s...,Uttar Pradesh,SHAHJAHANPUR(DISTRICT MAGISTRAE SHAHJAHANAPUR_...,Shri Arun Kumar Sagar,SHAHJAHANPUR(SC),Installation of 156 LED Highmast Lights for Ru...,2024-08-07,2024-08-28,...,736,0.0,9.0,2024-09-03,6.0,72.450764,89.0,-1,-0.230341,High Risk
40339,WS/MP18241/2025-2026/210661,Normal/Others,WS/MP18241/2025-2026/210661-Lighting of public...,Uttar Pradesh,SITAPUR(DISTRICT MAGISTRATE SITAPUR_IDA),RAKESH RATHOR,SITAPUR,Installation of 80 six way 200 watt electric h...,2025-06-20,2025-07-08,...,422,0.0,2.0,2025-10-10,94.0,25.578935,422.0,-1,-0.228730,High Risk
77911,WS/MP492/2026-2027/294027,Normal/Others,WS/MP492/2026-2027/294027-Construction of bus-...,Uttar Pradesh,SHAHJAHANPUR(DISTRICT MAGISTRAE SHAHJAHANAPUR_...,Shri Arun Kumar Sagar,SHAHJAHANPUR(SC),22 Yatri Tin Bus shades List for rural and Urb...,2026-07-10,2026-08-14,...,20,0.0,1.0,2026-08-26,12.0,27.776233,20.0,-1,-0.228436,High Risk

In [124]:
# View the most unusual work and its important risk indicators
high_risk.iloc[0][[
    "work_id",
    "Sanction Amount ( ₹ )",
    "Fund Disbursed Amount ( ₹ )",
    "expenditure_ratio",
    "duration_days",
    "sanction_delay_days",
    "payment_count",
    "vendor_count",
    "cost_vs_category_avg",
    "anomaly_score"
]]

work_id                        WS/MP507/2026-2027/290535
Sanction Amount ( ₹ )                         49740000.0
Fund Disbursed Amount ( ₹ )                   35321457.0
expenditure_ratio                               0.710122
duration_days                                       15.0
sanction_delay_days                                   50
payment_count                                        8.0
vendor_count                                         1.0
cost_vs_category_avg                           95.064393
anomaly_score                                  -0.264434
Name: 77185, dtype: object

In [125]:
# Flag works with unusually high cost compared with their category
final["high_cost_flag"] = final["cost_vs_category_avg"] > 2

In [127]:
# high_cost_flag: The work's sanctioned cost is more than 2× the average cost of similar works in its category.
# Count high-cost works
final["high_cost_flag"].value_counts()

high_cost_flag
False    71950
True      7002
Name: count, dtype: int64

In [128]:
# Flag works taking unusually long to execute
final["long_duration_flag"] = final["duration_days"] > 260

In [129]:
# Count long-duration works
final["long_duration_flag"].value_counts()

long_duration_flag
False    52765
True     26187
Name: count, dtype: int64

Creating risk reasons

In [130]:
# Create simple explanations for high-risk works
final["risk_reasons"] = ""

final.loc[final["high_cost_flag"], "risk_reasons"] += "High Cost; "
final.loc[final["long_duration_flag"], "risk_reasons"] += "Long Duration; "
final.loc[final["long_sanction_delay"], "risk_reasons"] += "Long Sanction Delay; "
final.loc[final["over_expenditure"] == True, "risk_reasons"] += "Over Expenditure; "

In [131]:
# View risk reasons for high-risk works
final[final["risk_level"] == "High Risk"][["work_id", "risk_reasons"]].head(10)

,work_id,risk_reasons
3,WS/MP620/2025-2026/133191,High Cost; Long Duration; Long Sanction Delay;
16,WS/MP498/2024-2025/133447,High Cost; Long Duration;
111,WS/MP641/2024-2025/133912,Long Duration;
153,WS/MP632/2024-2025/134091,High Cost; Long Duration;
167,WS/MP345/2024-2025/134123,High Cost;
174,WS/MP18182/2024-2025/134222,High Cost;
175,WS/MP18182/2024-2025/134223,High Cost;
176,WS/MP18182/2024-2025/134224,High Cost;
177,WS/MP18182/2024-2025/134225,High Cost;
186,WS/MP485/2024-2025/134332,High Cost;

Flag unusually high expenditure

In [132]:
# Flag works where expenditure has reached 90% or more of the sanctioned amount
final["high_expenditure_flag"] = final["expenditure_ratio"] >= 0.90

In [133]:
# Count works with high expenditure utilization
final["high_expenditure_flag"].value_counts()

high_expenditure_flag
True     47336
False    31616
Name: count, dtype: int64

In [134]:
# Add high expenditure to the risk explanation
final.loc[final["high_expenditure_flag"], "risk_reasons"] += "High Expenditure; "

In [135]:
# Check updated risk explanations
final[final["risk_level"] == "High Risk"][["work_id", "risk_reasons"]].head(10)

,work_id,risk_reasons
3,WS/MP620/2025-2026/133191,High Cost; Long Duration; Long Sanction Delay;
16,WS/MP498/2024-2025/133447,High Cost; Long Duration; High Expenditure;
111,WS/MP641/2024-2025/133912,Long Duration;
153,WS/MP632/2024-2025/134091,High Cost; Long Duration; High Expenditure;
167,WS/MP345/2024-2025/134123,High Cost; High Expenditure;
174,WS/MP18182/2024-2025/134222,High Cost; High Expenditure;
175,WS/MP18182/2024-2025/134223,High Cost; High Expenditure;
176,WS/MP18182/2024-2025/134224,High Cost; High Expenditure;
177,WS/MP18182/2024-2025/134225,High Cost; High Expenditure;
186,WS/MP485/2024-2025/134332,High Cost; High Expenditure;

Flag delayed first payments

In [136]:
# Flag works where the first payment took more than 90 days
final["late_first_payment_flag"] = final["first_payment_delay_days"] > 90

In [137]:
# Count works with delayed first payments
final["late_first_payment_flag"].value_counts()

late_first_payment_flag
False    50012
True     28940
Name: count, dtype: int64

In [138]:
# Add delayed first payment to the risk explanation
final.loc[
    final["late_first_payment_flag"],
    "risk_reasons"
] += "Late First Payment; "

In [139]:
# Check the updated risk explanations
final[final["risk_level"] == "High Risk"][["work_id", "risk_reasons"]].head(10)

,work_id,risk_reasons
3,WS/MP620/2025-2026/133191,High Cost; Long Duration; Long Sanction Delay;...
16,WS/MP498/2024-2025/133447,High Cost; Long Duration; High Expenditure; La...
111,WS/MP641/2024-2025/133912,Long Duration;
153,WS/MP632/2024-2025/134091,High Cost; Long Duration; High Expenditure; La...
167,WS/MP345/2024-2025/134123,High Cost; High Expenditure; Late First Payment;
174,WS/MP18182/2024-2025/134222,High Cost; High Expenditure;
175,WS/MP18182/2024-2025/134223,High Cost; High Expenditure;
176,WS/MP18182/2024-2025/134224,High Cost; High Expenditure;
177,WS/MP18182/2024-2025/134225,High Cost; High Expenditure;
186,WS/MP485/2024-2025/134332,High Cost; High Expenditure; Late First Payment;

Creating an overall risk score

In [140]:
# Calculate an explainable risk score from the warning indicators
risk_flags = [
    "high_cost_flag",
    "long_duration_flag",
    "long_sanction_delay",
    "over_expenditure",
    "high_expenditure_flag",
    "late_first_payment_flag"
]

final["risk_score"] = final[risk_flags].fillna(False).astype(int).sum(axis=1) / len(risk_flags) * 100

C:\Users\sneha\AppData\Local\Temp\ipykernel_12856\1534888327.py:11: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final["risk_score"] = final[risk_flags].fillna(False).astype(int).sum(axis=1) / len(risk_flags) * 100

In [141]:
# View the distribution of the explainable risk score
final["risk_score"].value_counts().sort_index()

risk_score
0.000000     11774
16.666667    25897
33.333333    23627
50.000000    14879
66.666667     2629
83.333333      146
Name: count, dtype: int64

**Human-readable risk categories** based on the number of triggered indicators: 

0–1 indicators → Low Risk;
2 indicators → Medium Risk;
3–4 indicators → High Risk;
5–6 indicators → Critical Risk;

0–16.67 → Low;
33.33 → Medium;
50–66.67 → High;
83.33–100 → Critical;

In [144]:
# Correct risk categories using the actual score ranges
def assign_risk_category(score):
    if score <= 16.67:
        return "Low Risk"
    elif score <= 33.34:
        return "Medium Risk"
    elif score <= 66.67:
        return "High Risk"
    else:
        return "Critical Risk"

final["final_risk_category"] = final["risk_score"].apply(assign_risk_category)

In [145]:
# Count works in each final risk category
final["final_risk_category"].value_counts()

final_risk_category
Low Risk         37671
Medium Risk      23627
High Risk        17508
Critical Risk      146
Name: count, dtype: int64

In [146]:
# Compare Isolation Forest results with our explainable risk categories
pd.crosstab(
    final["final_risk_category"],
    final["anomaly_prediction"]
)

anomaly_prediction     -1      1
final_risk_category
Critical Risk          63     83
High Risk            1942  15566
Low Risk              486  37185
Medium Risk          1457  22170

Calculating AI/rule agreement

In [147]:
# Check how many AI-anomalous works also have high/critical rule-based risk
ai_anomalous = final["anomaly_prediction"] == -1
rule_high_risk = final["risk_score"] >= 50

agreement_count = (ai_anomalous & rule_high_risk).sum()

print("AI anomalies:", ai_anomalous.sum())
print("High/Critical rule-based risks:", rule_high_risk.sum())
print("Both AI + rules flagged:", agreement_count)

AI anomalies: 3948
High/Critical rule-based risks: 17654
Both AI + rules flagged: 2005

Creating the final priority alert flag

In [148]:
# Create a final priority alert when both methods identify risk
final["priority_alert"] = (
    (final["anomaly_prediction"] == -1) &
    (final["risk_score"] >= 50)
)

In [149]:
# Count priority alerts
final["priority_alert"].value_counts()

priority_alert
False    76947
True      2005
Name: count, dtype: int64

Inspecting the priority alerts

In [151]:
# View the highest-priority cases for investigation
priority_cases = final[final["priority_alert"]].sort_values("anomaly_score")

priority_cases[[
    "work_id",
    "risk_score",
    "final_risk_category",
    "risk_reasons",
    "anomaly_score"
]].head(20)

,work_id,risk_score,final_risk_category,risk_reasons,anomaly_score
42488,WS/MP18198/2025-2026/214766,66.666667,High Risk,High Cost; Long Duration; High Expenditure; La...,-0.253937
9828,WS/MP18249/2025-2026/153601,66.666667,High Risk,High Cost; Long Duration; Long Sanction Delay;...,-0.244282
31991,WS/MP507/2025-2026/196288,50.000000,High Risk,High Cost; Long Duration; Late First Payment;,-0.242891
9829,WS/MP18249/2025-2026/153603,50.000000,High Risk,High Cost; Long Duration; Long Sanction Delay;,-0.237893
50171,WS/MP817/2025-2026/229416,50.000000,High Risk,High Cost; Long Duration; Late First Payment;,-0.236346
43541,WS/MP18279/2025-2026/216827,50.000000,High Risk,High Cost; Long Duration; Late First Payment;,-0.233450
40339,WS/MP18241/2025-2026/210661,50.000000,High Risk,High Cost; Long Duration; Late First Payment;,-0.228730
31018,WS/MP18198/2025-2026/193991,50.000000,High Risk,High Cost; High Expenditure; Late First Payment;,-0.227934
50173,WS/MP817/2025-2026/229418,50.000000,High Risk,High Cost; Long Duration; Late First Payment;,-0.227407
16832,WS/MP18070/2025-2026/166162,50.000000,High Risk,High Cost; Long Duration; Late First Payment;,-0.227402
43504,WS/MP18242/2025-2026/216762,83.333333,Critical Risk,High Cost; Long Duration; Long Sanction Delay;...,-0.225227
50169,WS/MP817/2025-2026/229414,50.000000,High Risk,High Cost; Long Duration; Late First Payment;,-0.224709
26220,WS/MP18174/2025-2026/184631,50.000000,High Risk,High Cost; Long Duration; Long Sanction Delay;,-0.224376
32367,WS/MP18192/2025-2026/196895,66.666667,High Risk,High Cost; Long Duration; High Expenditure; La...,-0.223960
7415,WS/MP18277/2025-2026/149810,66.666667,High Risk,High Cost; Long Duration; Long Sanction Delay;...,-0.222788
45888,WS/MP18197/2025-2026/221826,50.000000,High Risk,High Cost; Long Duration; Late First Payment;,-0.220880
40646,WS/MP880/2025-2026/211190,50.000000,High Risk,High Cost; Long Duration; Long Sanction Delay;,-0.219357
18796,WS/MP507/2024-2025/170558,50.000000,High Risk,High Cost; Long Duration; High Expenditure;,-0.219108
20135,WS/MP18241/2025-2026/174147,66.666667,High Risk,High Cost; Long Duration; High Expenditure; La...,-0.216882
1056,WS/MP823/2024-2025/137367,50.000000,High Risk,High Cost; Long Duration; Late First Payment;,-0.216012

Creating a final alert type

In [152]:
# Create a final alert type by combining AI and rule-based results
def assign_alert_type(row):
    if row["priority_alert"]:
        return "Priority Alert"
    elif row["anomaly_prediction"] == -1:
        return "AI Anomaly"
    elif row["risk_score"] >= 50:
        return "Rule-Based High Risk"
    else:
        return "Normal"

final["alert_type"] = final.apply(assign_alert_type, axis=1)

In [153]:
# Count works in each alert type
final["alert_type"].value_counts()

alert_type
Normal                  59355
Rule-Based High Risk    15649
Priority Alert           2005
AI Anomaly               1943
Name: count, dtype: int64

In [154]:
# Check the priority alerts and their main risk reasons
priority_cases[[
    "work_id",
    "risk_score",
    "final_risk_category",
    "risk_reasons",
    "anomaly_score"
]].head(20)

,work_id,risk_score,final_risk_category,risk_reasons,anomaly_score
42488,WS/MP18198/2025-2026/214766,66.666667,High Risk,High Cost; Long Duration; High Expenditure; La...,-0.253937
9828,WS/MP18249/2025-2026/153601,66.666667,High Risk,High Cost; Long Duration; Long Sanction Delay;...,-0.244282
31991,WS/MP507/2025-2026/196288,50.000000,High Risk,High Cost; Long Duration; Late First Payment;,-0.242891
9829,WS/MP18249/2025-2026/153603,50.000000,High Risk,High Cost; Long Duration; Long Sanction Delay;,-0.237893
50171,WS/MP817/2025-2026/229416,50.000000,High Risk,High Cost; Long Duration; Late First Payment;,-0.236346
43541,WS/MP18279/2025-2026/216827,50.000000,High Risk,High Cost; Long Duration; Late First Payment;,-0.233450
40339,WS/MP18241/2025-2026/210661,50.000000,High Risk,High Cost; Long Duration; Late First Payment;,-0.228730
31018,WS/MP18198/2025-2026/193991,50.000000,High Risk,High Cost; High Expenditure; Late First Payment;,-0.227934
50173,WS/MP817/2025-2026/229418,50.000000,High Risk,High Cost; Long Duration; Late First Payment;,-0.227407
16832,WS/MP18070/2025-2026/166162,50.000000,High Risk,High Cost; Long Duration; Late First Payment;,-0.227402
43504,WS/MP18242/2025-2026/216762,83.333333,Critical Risk,High Cost; Long Duration; Long Sanction Delay;...,-0.225227
50169,WS/MP817/2025-2026/229414,50.000000,High Risk,High Cost; Long Duration; Late First Payment;,-0.224709
26220,WS/MP18174/2025-2026/184631,50.000000,High Risk,High Cost; Long Duration; Long Sanction Delay;,-0.224376
32367,WS/MP18192/2025-2026/196895,66.666667,High Risk,High Cost; Long Duration; High Expenditure; La...,-0.223960
7415,WS/MP18277/2025-2026/149810,66.666667,High Risk,High Cost; Long Duration; Long Sanction Delay;...,-0.222788
45888,WS/MP18197/2025-2026/221826,50.000000,High Risk,High Cost; Long Duration; Late First Payment;,-0.220880
40646,WS/MP880/2025-2026/211190,50.000000,High Risk,High Cost; Long Duration; Long Sanction Delay;,-0.219357
18796,WS/MP507/2024-2025/170558,50.000000,High Risk,High Cost; Long Duration; High Expenditure;,-0.219108
20135,WS/MP18241/2025-2026/174147,66.666667,High Risk,High Cost; Long Duration; High Expenditure; La...,-0.216882
1056,WS/MP823/2024-2025/137367,50.000000,High Risk,High Cost; Long Duration; Late First Payment;,-0.216012

In [155]:
# Check which risk indicators are most common among priority alerts
priority_cases[risk_flags].sum().sort_values(ascending=False)

high_expenditure_flag      1609
high_cost_flag             1501
late_first_payment_flag    1474
long_duration_flag         1390
long_sanction_delay         724
over_expenditure              0
dtype: object

**Checking duplicate work descriptions**

In [157]:
# Check for repeated work descriptions within the same constituency
duplicate_candidates = final[
    final.duplicated(
        subset=["Constituency_x", "Work description"],
        keep=False
    )
].sort_values(["Constituency_x", "Work description"])

duplicate_candidates.shape

(8126, 45)

In [158]:
# Inspect possible duplicate works
duplicate_candidates[
    ["work_id", "Constituency_x", "Work description", "Sanction Amount ( ₹ )"]
].head(20)

,work_id,Constituency_x,Work description,Sanction Amount ( ₹ )
65689,WS/MP18053/2026-2027/260442,AHMEDABAD WEST(SC),ISHANPUR SENIOR CITIZEN PARK-4 Steel Benches,34400.0
65691,WS/MP18053/2026-2027/260444,AHMEDABAD WEST(SC),ISHANPUR SENIOR CITIZEN PARK-4 Steel Benches,34400.0
62830,WS/MP18198/2025-2026/254467,ALLAHABAD,Solar light install in allahabad lokasabha,1490806.0
62834,WS/MP18198/2025-2026/254471,ALLAHABAD,Solar light install in allahabad lokasabha,1368274.0
62836,WS/MP18198/2025-2026/254474,ALLAHABAD,Solar light install in allahabad lokasabha,918990.0
62840,WS/MP18198/2025-2026/254481,ALLAHABAD,Solar light install in allahabad lokasabha,1021100.0
62835,WS/MP18198/2025-2026/254473,ALLAHABAD,Solar light install in allahabad loksabha,857724.0
62842,WS/MP18198/2026-2027/254483,ALLAHABAD,Solar light install in allahabad loksabha,776036.0
62843,WS/MP18198/2025-2026/254484,ALLAHABAD,Solar light install in allahabad loksabha,1184476.0
43527,WS/MP18060/2025-2026/216799,AMBALA (SC),Construction of BC Choupal,1300000.0
51298,WS/MP18060/2025-2026/231642,AMBALA (SC),Construction of BC Choupal,1300000.0
38424,WS/MP18060/2025-2026/207464,AMBALA (SC),Construction of General Choupal,1200000.0
39678,WS/MP18060/2025-2026/209349,AMBALA (SC),Construction of General Choupal,1200000.0
39680,WS/MP18060/2025-2026/209351,AMBALA (SC),Construction of General Choupal,1438000.0
37097,WS/MP18060/2025-2026/205026,AMBALA (SC),Construction of Hall,1200000.0
38420,WS/MP18060/2025-2026/207460,AMBALA (SC),Construction of Hall,1200000.0
39483,WS/MP18060/2025-2026/209044,AMBALA (SC),Construction of Hall,1200000.0
39676,WS/MP18060/2025-2026/209344,AMBALA (SC),Construction of Hall,1200000.0
39677,WS/MP18060/2025-2026/209346,AMBALA (SC),Construction of Hall,1200000.0
39695,WS/MP18060/2025-2026/209438,AMBALA (SC),Construction of Hall,1500000.0

In [159]:
# Check whether the final dataset has duplicate Work IDs
final["work_id"].duplicated().sum()

np.int64(0)

In [160]:
# Inspect the main risk indicators for priority alerts
priority_cases[[
    "work_id",
    "Sanction Amount ( ₹ )",
    "Fund Disbursed Amount ( ₹ )",
    "expenditure_ratio",
    "duration_days",
    "sanction_delay_days",
    "payment_count",
    "vendor_count",
    "cost_vs_category_avg",
    "risk_score",
    "risk_reasons",
    "anomaly_score"
]].head(10)

,work_id,Sanction Amount ( ₹ ),Fund Disbursed Amount ( ₹ ),expenditure_ratio,duration_days,sanction_delay_days,payment_count,vendor_count,cost_vs_category_avg,risk_score,risk_reasons,anomaly_score
42488,WS/MP18198/2025-2026/214766,16757000.0,15862312.0,0.946608,387.0,39,22.0,11.0,32.026418,66.666667,High Cost; Long Duration; High Expenditure; La...,-0.253937
9828,WS/MP18249/2025-2026/153601,20000000.0,8945913.0,0.447296,381.0,270,2.0,2.0,38.224525,66.666667,High Cost; Long Duration; Long Sanction Delay;...,-0.244282
31991,WS/MP507/2025-2026/196288,47472048.0,37203872.0,0.783701,434.0,54,4.0,1.0,90.729824,50.000000,High Cost; Long Duration; Late First Payment;,-0.242891
9829,WS/MP18249/2025-2026/153603,20000000.0,15604993.0,0.780250,381.0,270,4.0,2.0,38.224525,50.000000,High Cost; Long Duration; Long Sanction Delay;,-0.237893
50171,WS/MP817/2025-2026/229416,22131000.0,17151917.0,0.775018,357.0,16,2.0,1.0,42.297348,50.000000,High Cost; Long Duration; Late First Payment;,-0.236346
43541,WS/MP18279/2025-2026/216827,45000000.0,32562250.0,0.723606,393.0,27,1.0,1.0,86.005181,50.000000,High Cost; Long Duration; Late First Payment;,-0.233450
40339,WS/MP18241/2025-2026/210661,13383520.0,10010880.0,0.748001,422.0,18,2.0,1.0,25.578935,50.000000,High Cost; Long Duration; Late First Payment;,-0.228730
31018,WS/MP18198/2025-2026/193991,9860000.0,9464338.0,0.959872,164.0,83,17.0,8.0,16.144943,50.000000,High Cost; High Expenditure; Late First Payment;,-0.227934
50173,WS/MP817/2025-2026/229418,19747300.0,16945492.0,0.858117,357.0,16,2.0,1.0,37.741558,50.000000,High Cost; Long Duration; Late First Payment;,-0.227407
16832,WS/MP18070/2025-2026/166162,15000000.0,6894000.0,0.459600,456.0,138,1.0,1.0,28.668394,50.000000,High Cost; Long Duration; Late First Payment;,-0.227402

Calculating the percentage of works detected as AI anomalies

In [161]:
# Calculate the percentage of works identified as AI anomalies
anomaly_percentage = (final["anomaly_prediction"] == -1).mean() * 100

print("AI Anomalies:", (final["anomaly_prediction"] == -1).sum())
print("Total Works:", len(final))
print("Anomaly Percentage:", round(anomaly_percentage, 2), "%")

AI Anomalies: 3948
Total Works: 78952
Anomaly Percentage: 5.0 %

Checking the maximum expenditure ratio

In [162]:
# Check whether any work has expenditure greater than its sanctioned amount
final["expenditure_ratio"].max()

np.float64(1.0)

**Saving the final ML/risk dataset**

In [165]:
final.to_csv("MPLADS_final_risk_dataset.csv", index=False)

print("Final dataset saved successfully.")

Final dataset saved successfully.

In [170]:
final.head()

,work_id,Work category,Work_x,State_x,IDA_x,Hon'ble Members of Parliament_x,Constituency_x,Work description,Recommended date,Sanction Date,...,risk_level,high_cost_flag,long_duration_flag,risk_reasons,high_expenditure_flag,late_first_payment_flag,risk_score,final_risk_category,priority_alert,alert_type
0,WS/MP620/2024-2025/133166,Normal/Others,WS/ MP620/2024-2025/133166-Construction of bui...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan at Navalgund ...,2024-07-08,2024-07-09,...,Normal,False,False,High Expenditure; Late First Payment;,True,True,33.333333,Medium Risk,False,Normal
1,WS/MP620/2025-2026/133167,Trust and Society,WS/ MP620/2025-2026/133167-Construction of roo...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of College room of CBS Charitabl...,2024-07-08,2025-09-18,...,Normal,False,True,Long Duration; Long Sanction Delay;,False,False,33.333333,Medium Risk,False,Normal
2,WS/MP620/2024-2025/133190,Trust and Society,WS/ MP620/2024-2025/133190-Construction of bui...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan of Veerashaiv...,2024-07-08,2024-09-23,...,Normal,False,True,Long Duration;,False,False,16.666667,Low Risk,False,Normal
3,WS/MP620/2025-2026/133191,Normal/Others,WS/ MP620/2025-2026/133191-Construction of bui...,Karnataka,HAVERI(DEPUTY COMMISSIONER HAVERI_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Maremma Cultural bhavan at Nee...,2024-07-08,2025-05-29,...,High Risk,True,True,High Cost; Long Duration; Long Sanction Delay;...,False,True,66.666667,High Risk,True,Priority Alert
4,WS/MP620/2024-2025/133301,Normal/Others,WS/ MP620/2024-2025/133301-Construction of bui...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Cultural Bhavan at Kundagol TQ...,2024-07-09,2024-08-22,...,Normal,False,False,High Expenditure; Late First Payment;,True,True,33.333333,Medium Risk,False,Normal

In [169]:
final.shape

(78952, 45)

**Dashboard Dataset Preparation**

In [172]:
# Select the key fields needed for the MPLADS monitoring dashboard

dashboard_columns = [
    "work_id",
    "Work category",
    "State_x",
    "Constituency_x",
    "Sanction Amount ( ₹ )",
    "Fund Disbursed Amount ( ₹ )",
    "expenditure_ratio",
    "duration_days",
    "sanction_delay_days",
    "payment_count",
    "vendor_count",
    "cost_vs_category_avg",
    "risk_score",
    "final_risk_category",
    "alert_type",
    "risk_reasons"
]

dashboard_data = final[dashboard_columns].copy()

print("Dashboard dataset shape:", dashboard_data.shape)

Dashboard dataset shape: (78952, 16)

In [173]:
dashboard_data.head()

,work_id,Work category,State_x,Constituency_x,Sanction Amount ( ₹ ),Fund Disbursed Amount ( ₹ ),expenditure_ratio,duration_days,sanction_delay_days,payment_count,vendor_count,cost_vs_category_avg,risk_score,final_risk_category,alert_type,risk_reasons
0,WS/MP620/2024-2025/133166,Normal/Others,Karnataka,DHARWAD,497185.0,497185.0,1.000000,97.0,1,1.0,1.0,0.950233,33.333333,Medium Risk,Normal,High Expenditure; Late First Payment;
1,WS/MP620/2025-2026/133167,Trust and Society,Karnataka,DHARWAD,500000.0,0.0,0.000000,350.0,437,0.0,0.0,0.511002,33.333333,Medium Risk,Normal,Long Duration; Long Sanction Delay;
2,WS/MP620/2024-2025/133190,Trust and Society,Karnataka,DHARWAD,450000.0,0.0,0.000000,710.0,77,0.0,0.0,0.459902,16.666667,Low Risk,Normal,Long Duration;
3,WS/MP620/2025-2026/133191,Normal/Others,Karnataka,DHARWAD,1500000.0,850909.0,0.567273,462.0,325,1.0,1.0,2.866839,66.666667,High Risk,Priority Alert,High Cost; Long Duration; Long Sanction Delay;...
4,WS/MP620/2024-2025/133301,Normal/Others,Karnataka,DHARWAD,398009.0,398009.0,1.000000,165.0,44,1.0,1.0,0.760685,33.333333,Medium Risk,Normal,High Expenditure; Late First Payment;

In [174]:
# Save the compact dashboard dataset for the prototype
dashboard_data.to_csv("MPLADS_dashboard_data.csv", index=False)

print("Dashboard dataset saved successfully.")

Dashboard dataset saved successfully.